version: "3.3"
services:
  db:
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQLS_DB}

      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./mysql:/var/lib/mysql/

volumes:
  mysql:
